# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aharrass <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/06 20:48:11 by aharrass          #+#    #+#              #
#    Updated: 2023/03/16 20:56:50 by aharrass         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a

SRCS	=	ft_isalpha.c		\
				ft_isprint.c		\
				ft_isdigit.c		\
				ft_isalnum.c		\
				ft_isascii.c		\
				ft_toupper.c		\
				ft_tolower.c		\
				ft_strlen.c			\
				ft_strchr.c			\
				ft_strrchr.c		\
				ft_memset.c			\
				ft_strncmp.c		\
				ft_strcmp.c			\
				ft_atoi.c				\
				ft_strlcat.c		\
				ft_strlcpy.c		\
				ft_bzero.c			\
				ft_strnstr.c		\
				ft_memcpy.c			\
				ft_memmove.c		\
				ft_memcmp.c			\
				ft_memchr.c			\
				ft_calloc.c			\
				ft_strdup.c			\
				ft_substr.c			\
				ft_strjoin.c		\
				ft_strjoin1.c		\
				ft_strjoin2.c		\
				ft_strtrim.c		\
				ft_split.c			\
				ft_itoa.c				\
				ft_strmapi.c		\
				ft_striteri.c		\
				ft_putchar_fd.c	\
				ft_putstr_fd.c	\
				ft_putendl_fd.c	\
				ft_putnbr_fd.c	\
				ft_strjoin3.c		\
				free_me.c				\
				ft_split_qk.c		\
				ft_strcmp2.c		\
				

OB_PATH = ../obj/

OBJS	=	${addprefix ${OB_PATH}, ${SRCS:.c=.o}}

CC		=	cc

RM		=	rm -f

CFLAGS	=	-Wall -Wextra -Werror

all:		${NAME}

${OB_PATH}%.o : %.c
			@mkdir -p ${OB_PATH}
			cc ${CFLAGS} -c $< -o $@

${NAME}:	${OBJS}
			ar -rcs ${NAME} ${OBJS}

clean:
			${RM} ${OBJS}

fclean:		clean
			${RM} ${NAME}

re:			fclean all

.PHONY:		all clean fclean re
